Repository jamz903/SimpCity, pull requests merged in 2021-12, with the labels that each got.

#19 Created function start_new_game
  start_new_game.py
Labels: feature, size_xs

#27 Created function display_board()
  display_board.py
Labels: feature, size_xs

#21 Created function start_menu() & play_menu()
  play_menu.py
  start_menu.py
Labels: feature, size_m

#18 Created function load_saved_game()
  load_saved_game.py
Labels: feature, size_s

#28 v1.0
  .github/workflows/pullRequest.yml
  SimpCity.py
  display_board.py
  load_saved_game.py
  play_menu.py
  start_menu.py
  start_new_game.py
Labels: release

#32 US2 ,US3 & US5
  convert_board_coords_to_index.py
  load_saved_game.py
  place_building.py
  start_game.py
  start_new_game.py
Labels: enhancement, feature, size_xl

#34 US 1, US 2, US 3, US 5, US 6 and US 9
  display_board.py
  generate_new_game_buildings.py
  pick_buildings.py
  play_menu.py
  see_remaining_buildings.py
  start_menu.py
Labels: feature, size_m

#35 v1.1
  convert_board_coords_to_index.py
  display_board.py
  generate_new_game_buildings.py
  load_saved_game.py
  pick_buildings.py
  place_building.py
  play_menu.py
  see_remaining_buildings.py
  start_game.py
  start_menu.py
  start_new_game.py
Labels: release
