Repository jamz903/SimpCity, pull requests merged in 2022-01, with the labels that each got.

#46 Created validation for load game
  start_game.py
  validate_saved_file.py
Labels: enhancement, size_l

#51 Created functions for save_game() and view_score()
  save_game.py
  view_score.py
Labels: feature, size_xl

#60 Created function to display final layout and end game
  check_game_end.py
  display_board.py
  final_layout.py
  play_menu.py
  start_game.py
Labels: feature, size_m

#63 v1.2
  .github/workflows/delivery.yml
  .github/workflows/pushPull-main.yml
  check_game_end.py
  display_board.py
  final_layout.py
  play_menu.py
  save_game.py
  start_game.py
  validate_saved_file.py
  view_score.py
Labels: release
